from django.db import models

# Create your models here.


class PVCProduct(models.Model):
  material =models.CharField(max_length=250,blank=True,null=True)
  artikul =models.CharField(max_length=250,blank=True,null=True)
  section =models.CharField(max_length=100,blank=True,null=True)
  counter =models.IntegerField(default=0)
  gruppa_materialov =models.CharField(max_length=250,blank=True,null=True)
  kratkiy_tekst_materiala =models.CharField(max_length= 250,blank = True, null = True)
  created_at =models.DateTimeField(auto_now_add = True)
  updated_at =models.DateTimeField(auto_now = True)

class PVCFile(models.Model):
  file =  models.FileField(upload_to='uploads/pvc/downloads/',max_length=500)
  file_type = models.CharField(max_length=255,blank=True,null=True)
  created_at =  models.DateTimeField(auto_now_add=True)
  updated_at =  models.DateTimeField(auto_now=True)
  

class Characteristika(models.Model):
  sap_code =models.CharField(max_length=255,blank=True,null=True)
  kratkiy_text =models.CharField(max_length=255,blank=True,null=True)
  section =models.CharField(max_length=255,blank=True,null=True)
  savdo_id =models.CharField(max_length=255,blank=True,null=True)
  savdo_name =models.CharField(max_length=255,blank=True,null=True)
  export_customer_id =models.CharField(max_length=255,blank=True,null=True)
  system =models.CharField(max_length=255,blank=True,null=True)
  article =models.CharField(max_length=255,blank=True,null=True)
  length =models.CharField(max_length=255,blank=True,null=True)
  surface_treatment =models.CharField(max_length=255,blank=True,null=True)
  alloy =models.CharField(max_length=255,blank=True,null=True)
  temper =models.CharField(max_length=255,blank=True,null=True)
  combination =models.CharField(max_length=255,blank=True,null=True)
  outer_side_pc_id =models.CharField(max_length=255,blank=True,null=True)
  outer_side_pc_brand =models.CharField(max_length=255,blank=True,null=True)
  inner_side_pc_id =models.CharField(max_length=255,blank=True,null=True)
  inner_side_pc_brand =models.CharField(max_length=255,blank=True,null=True)
  outer_side_wg_s_id =models.CharField(max_length=255,blank=True,null=True)
  inner_side_wg_s_id =models.CharField(max_length=255,blank=True,null=True)
  outer_side_wg_id =models.CharField(max_length=255,blank=True,null=True)
  inner_side_wg_id =models.CharField(max_length=255,blank=True,null=True)
  anodization_contact =models.CharField(max_length=255,blank=True,null=True)
  anodization_type =models.CharField(max_length=255,blank=True,null=True)
  anodization_method =models.CharField(max_length=255,blank=True,null=True)
  print_view =models.CharField(max_length=255,blank=True,null=True)
  profile_base =models.CharField(max_length=255,blank=True,null=True)
  width =models.CharField(max_length=255,blank=True,null=True)
  height =models.CharField(max_length=255,blank=True,null=True)
  category =models.CharField(max_length=255,blank=True,null=True)
  rawmat_type =models.CharField(max_length=255,blank=True,null=True)
  benkam_id =models.CharField(max_length=255,blank=True,null=True)
  hollow_and_solid =models.CharField(max_length=255,blank=True,null=True)
  export_description =models.CharField(max_length=255,blank=True,null=True)
  export_description_eng =models.CharField(max_length=255,blank=True,null=True)
  tnved =models.CharField(max_length=255,blank=True,null=True)
  surface_treatment_export =models.CharField(max_length=255,blank=True,null=True)
  wms_width =models.CharField(max_length=255,blank=True,null=True)
  wms_height =models.CharField(max_length=255,blank=True,null=True)
  group_prise =models.CharField(max_length=255,blank=True,null=True)
  created_at =models.DateTimeField(auto_now_add=True)
  updated_at =models.DateTimeField(auto_now=True)