# Generated by Django 5.0.4 on 2024-07-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiator', '0005_vifiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadiatorSapCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(blank=True, max_length=250, null=True)),
                ('artikul', models.CharField(blank=True, max_length=250, null=True)),
                ('section', models.CharField(blank=True, max_length=100, null=True)),
                ('counter', models.IntegerField(default=0)),
                ('kratkiy_tekst_materiala', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RazlovkaRadiator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_sap_code', models.CharField(max_length=100)),
                ('pr_kratkiy', models.CharField(max_length=150)),
                ('mo_sap_code', models.CharField(max_length=100)),
                ('mo_kratkiy', models.CharField(max_length=150)),
                ('pm_sap_code', models.CharField(max_length=100)),
                ('pm_kratkiy', models.CharField(max_length=150)),
                ('pk_sap_code', models.CharField(max_length=100)),
                ('pk_kratkiy', models.CharField(max_length=150)),
                ('sap_code7', models.CharField(max_length=100)),
                ('kratkiy7', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
