# Generated by Django 5.0.4 on 2024-07-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiator', '0006_radiatorsapcode_razlovkaradiator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiatorsapcode',
            name='section',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
