# Generated by Django 5.0.4 on 2024-07-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiator', '0008_artikulradiator'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikulradiator',
            name='model_radiator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
