# Generated by Django 5.0.4 on 2024-07-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiator', '0009_artikulradiator_model_radiator'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadiatorFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to='uploads/radiator/downloads/')),
                ('generated', models.BooleanField(default=False)),
                ('file_type', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
