# Generated by Django 5.0.4 on 2024-07-25 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiator', '0010_radiatorfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRadiator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('status', models.SmallIntegerField(choices=[(1, 'ON HOLD'), (2, 'ON PROCESS'), (3, 'CANCEL'), (4, 'DONE')], default=1)),
                ('work_type', models.SmallIntegerField(choices=[(1, 'ON HOLD'), (2, 'SAP CODE CREATING'), (3, 'SAP CODE CREATING LACKS'), (4, 'TEXT CREATING'), (5, 'TEXT CREATING LACKS'), (6, 'DONE')], default=1)),
                ('paths', models.JSONField(blank=True, default=dict, null=True)),
                ('order_type', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='on_time_worker_radiator', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('radiator_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radiator_work', to=settings.AUTH_USER_MODEL)),
                ('radiator_wrongs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radiator_work_wrong', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
