# Generated by Django 5.0.4 on 2024-09-03 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radiator', '0016_normaaurora_razlovkaradiatoraurora'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NormaAurora',
        ),
    ]
