# Generated by Django 5.0.4 on 2024-10-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiator', '0017_delete_normaaurora'),
    ]

    operations = [
        migrations.AddField(
            model_name='razlovkaradiatoraurora',
            name='es_kratkiy',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='razlovkaradiatoraurora',
            name='es_sap_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
