# Generated by Django 4.0 on 2024-04-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_orderdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
    ]
