# Generated by Django 5.0.4 on 2024-09-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_orderhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
