# Generated by Django 5.0.4 on 2024-10-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_orderhistory_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='is_opened',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
