# Generated by Django 5.0.4 on 2024-08-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessuar_import', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessuarImportSapCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(blank=True, max_length=25, null=True)),
                ('artikul', models.CharField(blank=True, max_length=20, null=True)),
                ('section', models.CharField(blank=True, max_length=10, null=True)),
                ('counter', models.IntegerField(default=0)),
                ('kratkiy_tekst_materiala', models.CharField(blank=True, max_length=80, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
