# Generated by Django 5.0.4 on 2024-09-17 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kraska', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Norma75',
        ),
    ]
