# Generated by Django 5.0.4 on 2024-10-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kraska', '0007_orderkraska'),
    ]

    operations = [
        migrations.CreateModel(
            name='KraskaSapCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(blank=True, max_length=250, null=True)),
                ('artikul', models.CharField(blank=True, max_length=250, null=True)),
                ('section', models.CharField(blank=True, max_length=10, null=True)),
                ('counter', models.IntegerField(default=0)),
                ('kratkiy_tekst_materiala', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
