# Generated by Django 3.2.20 on 2023-09-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_code', models.CharField(blank=True, max_length=255, null=True)),
                ('kratkiy_text', models.CharField(blank=True, max_length=255, null=True)),
                ('section', models.CharField(blank=True, max_length=255, null=True)),
                ('savdo_id', models.CharField(blank=True, max_length=255, null=True)),
                ('savdo_name', models.CharField(blank=True, max_length=255, null=True)),
                ('export_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('system', models.CharField(blank=True, max_length=255, null=True)),
                ('article', models.CharField(blank=True, max_length=255, null=True)),
                ('length', models.CharField(blank=True, max_length=255, null=True)),
                ('surface_treatment', models.CharField(blank=True, max_length=255, null=True)),
                ('alloy', models.CharField(blank=True, max_length=255, null=True)),
                ('temper', models.CharField(blank=True, max_length=255, null=True)),
                ('combination', models.CharField(blank=True, max_length=255, null=True)),
                ('outer_side_pc_id', models.CharField(blank=True, max_length=255, null=True)),
                ('outer_side_pc_brand', models.CharField(blank=True, max_length=255, null=True)),
                ('inner_side_pc_id', models.CharField(blank=True, max_length=255, null=True)),
                ('inner_side_pc_brand', models.CharField(blank=True, max_length=255, null=True)),
                ('outer_side_wg_s_id', models.CharField(blank=True, max_length=255, null=True)),
                ('inner_side_wg_s_id', models.CharField(blank=True, max_length=255, null=True)),
                ('outer_side_wg_id', models.CharField(blank=True, max_length=255, null=True)),
                ('inner_side_wg_id', models.CharField(blank=True, max_length=255, null=True)),
                ('anodization_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('anodization_type', models.CharField(blank=True, max_length=255, null=True)),
                ('anodization_method', models.CharField(blank=True, max_length=255, null=True)),
                ('print_view', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_base', models.CharField(blank=True, max_length=255, null=True)),
                ('width', models.CharField(blank=True, max_length=255, null=True)),
                ('height', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('rawmat_type', models.CharField(blank=True, max_length=255, null=True)),
                ('benkam_id', models.CharField(blank=True, max_length=255, null=True)),
                ('hollow_and_solid', models.CharField(blank=True, max_length=255, null=True)),
                ('export_description', models.CharField(blank=True, max_length=255, null=True)),
                ('export_description_eng', models.CharField(blank=True, max_length=255, null=True)),
                ('tnved', models.CharField(blank=True, max_length=255, null=True)),
                ('surface_treatment_export', models.CharField(blank=True, max_length=255, null=True)),
                ('wms_width', models.CharField(blank=True, max_length=255, null=True)),
                ('wms_height', models.CharField(blank=True, max_length=255, null=True)),
                ('group_prise', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PVCFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to='uploads/pvc/downloads/')),
                ('file_type', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PVCProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(blank=True, max_length=250, null=True)),
                ('artikul', models.CharField(blank=True, max_length=250, null=True)),
                ('section', models.CharField(blank=True, max_length=100, null=True)),
                ('counter', models.IntegerField(default=0)),
                ('gruppa_materialov', models.CharField(blank=True, max_length=250, null=True)),
                ('kratkiy_tekst_materiala', models.CharField(blank=True, max_length=250, null=True)),
                ('tip_pokritiya', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
