# Generated by Django 3.2.20 on 2023-09-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvc', '0002_remove_pvcproduct_tip_pokritiya'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtikulKomponentPVC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artikul', models.CharField(max_length=50)),
                ('component', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
