# Generated by Django 3.2.20 on 2023-09-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvc', '0004_artikulkomponentpvc_component2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikulkomponentpvc',
            name='component2',
            field=models.CharField(default='', max_length=50),
        ),
    ]
