# Generated by Django 3.2.20 on 2023-09-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvc', '0005_alter_artikulkomponentpvc_component2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikulkomponentpvc',
            name='component2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
