# Generated by Django 3.2.20 on 2023-09-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvc', '0006_alter_artikulkomponentpvc_component2'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikulkomponentpvc',
            name='shirina',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='artikulkomponentpvc',
            name='visota',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
