# Generated by Django 3.2.20 on 2023-09-29 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pvc', '0007_auto_20230928_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characteristika',
            old_name='alloy',
            new_name='amount_in_a_package',
        ),
        migrations.RenameField(
            model_name='characteristika',
            old_name='anodization_contact',
            new_name='ch_klaes_optm',
        ),
        migrations.RenameField(
            model_name='characteristika',
            old_name='anodization_method',
            new_name='ch_profile_type',
        ),
        migrations.RenameField(
            model_name='characteristika',
            old_name='anodization_type',
            new_name='coating_qbic',
        ),
        migrations.RenameField(
            model_name='characteristika',
            old_name='benkam_id',
            new_name='goods_group',
        ),
        migrations.RenameField(
            model_name='characteristika',
            old_name='combination',
            new_name='id_savdo',
        ),
        migrations.RenameField(
            model_name='characteristika',
            old_name='export_customer_id',
            new_name='klaes',
        ),
        migrations.RenameField(
            model_name='characteristika',
            old_name='export_description',
            new_name='kls_wast',
        ),
        migrations.RenameField(
            model_name='characteristika',
            old_name='export_description_eng',
            new_name='kls_wast_length',
        ),
        migrations.RenameField(
            model_name='characteristika',
            old_name='group_prise',
            new_name='material_class',
        ),
        migrations.RenameField(
            model_name='characteristika',
            old_name='hollow_and_solid',
            new_name='number_of_chambers',
        ),
        migrations.RenameField(
            model_name='characteristika',
            old_name='inner_side_pc_brand',
            new_name='product_type',
        ),
        migrations.RenameField(
            model_name='characteristika',
            old_name='inner_side_pc_id',
            new_name='profile_type',
        ),
        migrations.RenameField(
            model_name='characteristika',
            old_name='inner_side_wg_s_id',
            new_name='profile_type_id',
        ),
        migrations.RenameField(
            model_name='characteristika',
            old_name='kratkiy_text',
            new_name='sealer_color',
        ),
        migrations.RemoveField(
            model_name='characteristika',
            name='outer_side_pc_brand',
        ),
        migrations.RemoveField(
            model_name='characteristika',
            name='outer_side_wg_s_id',
        ),
        migrations.RemoveField(
            model_name='characteristika',
            name='profile_base',
        ),
        migrations.RemoveField(
            model_name='characteristika',
            name='savdo_id',
        ),
        migrations.RemoveField(
            model_name='characteristika',
            name='savdo_name',
        ),
        migrations.RemoveField(
            model_name='characteristika',
            name='section',
        ),
        migrations.RemoveField(
            model_name='characteristika',
            name='temper',
        ),
    ]
