# Generated by Django 3.2.20 on 2023-10-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvc', '0008_auto_20230929_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artikulkomponentpvc',
            old_name='shirina',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='artikulkomponentpvc',
            old_name='visota',
            new_name='height',
        ),
        migrations.AddField(
            model_name='artikulkomponentpvc',
            name='product_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='artikulkomponentpvc',
            name='profile_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='artikulkomponentpvc',
            name='tnved',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='artikulkomponentpvc',
            name='width',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='artikulkomponentpvc',
            name='wms_height',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='artikulkomponentpvc',
            name='wms_width',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
