# Generated by Django 3.2.20 on 2023-10-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvc', '0010_camerapvc'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbreviaturaLamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abreviatura', models.CharField(blank=True, max_length=50, null=True)),
                ('pokritiya', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
