# Generated by Django 3.2.20 on 2023-10-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvc', '0011_abreviaturalamination'),
    ]

    operations = [
        migrations.CreateModel(
            name='LengthOfProfilePVC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artikul', models.CharField(max_length=100)),
                ('length', models.CharField(max_length=150)),
                ('ves_za_shtuk', models.CharField(max_length=150)),
                ('ves_za_metr', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
