# Generated by Django 3.2.20 on 2023-10-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvc', '0013_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='zames',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
