# Generated by Django 3.2.20 on 2023-10-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvc', '0014_price_zames'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristika',
            name='kratkiy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
