# Generated by Django 3.2.20 on 2023-10-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvc', '0016_characteristikafilepvc'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazlovkaPVX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esapkode', models.CharField(blank=True, max_length=50, null=True)),
                ('ekrat', models.CharField(blank=True, max_length=50, null=True)),
                ('lsapkode', models.CharField(blank=True, max_length=50, null=True)),
                ('lkrat', models.CharField(blank=True, max_length=50, null=True)),
                ('sapkode7', models.CharField(blank=True, max_length=50, null=True)),
                ('krat7', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
