# Generated by Django 3.2.20 on 2023-10-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvc', '0017_razlovkapvx'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuxgalterskiyNazvaniye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naz_ru', models.CharField(blank=True, max_length=150, null=True)),
                ('naz_eng', models.CharField(blank=True, max_length=150, null=True)),
                ('sb', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
