# Generated by Django 3.2.20 on 2023-11-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvc', '0022_auto_20231101_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvcproduct',
            name='standart_price',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
