# Generated by Django 3.2.20 on 2023-11-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvc', '0023_pvcproduct_standart_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='BazaQbic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
