# Generated by Django 3.2.20 on 2023-11-06 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pvc', '0024_bazaqbic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BazaQbic',
        ),
    ]
