# Generated by Django 4.0 on 2024-03-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvc', '0025_delete_bazaqbic'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikulkomponentpvc',
            name='nazvaniye_sistem',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
