# Generated by Django 4.0 on 2024-03-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvc', '0027_artikulkomponentpvc_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikulkomponentpvc',
            name='kod_k_component',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
