# Generated by Django 5.0.4 on 2024-06-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvc', '0030_artikulkomponentpvc_iskyucheniye'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvcproduct',
            name='is_special',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='pvcproduct',
            name='rezina_isklyucheniya',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
