# Generated by Django 5.0.4 on 2024-06-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvc', '0031_pvcproduct_is_special_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pvcproduct',
            name='is_special',
        ),
        migrations.RemoveField(
            model_name='pvcproduct',
            name='rezina_isklyucheniya',
        ),
        migrations.AddField(
            model_name='artikulkomponentpvc',
            name='is_special',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='artikulkomponentpvc',
            name='rezina_isklyucheniya',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
