# Generated by Django 5.0.4 on 2024-06-05 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pvc', '0032_remove_pvcproduct_is_special_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artikulkomponentpvc',
            name='rezina_isklyucheniya',
        ),
    ]
