# Generated by Django 5.0.4 on 2024-06-05 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pvc', '0033_remove_artikulkomponentpvc_rezina_isklyucheniya'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RezinaIsklyucheniye',
        ),
    ]
