# Generated by Django 5.0.4 on 2024-07-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvc', '0034_delete_rezinaisklyucheniye'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikulkomponentpvc',
            name='nakleyka_nt1',
            field=models.CharField(blank=True, default='0', max_length=5, null=True),
        ),
    ]
