# Generated by Django 5.0.4 on 2024-07-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvc', '0035_artikulkomponentpvc_nakleyka_nt1'),
    ]

    operations = [
        migrations.AddField(
            model_name='abreviaturalamination',
            name='coating_qbic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='abreviaturalamination',
            name='surface_treatment_export',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='abreviaturalamination',
            name='surface_treatment_export_na',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='abreviaturalamination',
            name='surface_treatment_export_vn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
