# Generated by Django 5.0.4 on 2024-11-05 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0002_razlovkapvx'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RazlovkaPVX',
            new_name='RazlovkaMatrix',
        ),
    ]
