# Generated by Django 4.0 on 2024-01-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessuar', '0002_siryo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TexcartaBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
