# Generated by Django 5.0.4 on 2024-07-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jira_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
