# Generated by Django 3.2.20 on 2023-10-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesavdo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineSavdoOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paths', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
