# Generated by Django 3.2.20 on 2023-10-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesavdo', '0002_onlinesavdoorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinesavdoorder',
            name='file_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='onlinesavdoorder',
            name='parent',
            field=models.IntegerField(default=0),
        ),
    ]
