# Generated by Django 3.2.20 on 2023-10-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesavdo', '0003_auto_20231025_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinesavdofile',
            name='file',
            field=models.FileField(max_length=500, upload_to='uploads/online_savdo/downloads/'),
        ),
    ]
