# Generated by Django 5.0.4 on 2024-10-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesavdo', '0004_alter_onlinesavdofile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinesavdoorder',
            name='status',
            field=models.SmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
