# Generated by Django 3.2.15 on 2023-03-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_code_materials', models.CharField(blank=True, max_length=100, null=True)),
                ('ktartkiy_tekst_materiala', models.CharField(blank=True, max_length=255, null=True)),
                ('sap_kod_del_otxod', models.CharField(blank=True, max_length=100, null=True)),
                ('new_sap_kod_del_otxod', models.CharField(blank=True, max_length=100, null=True)),
                ('kratkiy_tekst_del_otxod', models.CharField(blank=True, max_length=200, null=True)),
                ('id_klaes', models.CharField(blank=True, max_length=100, null=True)),
                ('ch_profile_type', models.CharField(blank=True, max_length=100, null=True)),
                ('kls_wast', models.CharField(blank=True, max_length=50, null=True)),
                ('kls_wast_length', models.CharField(blank=True, max_length=50, null=True)),
                ('ch_kls_optom', models.CharField(blank=True, max_length=10, null=True)),
                ('kls_inner_id', models.CharField(blank=True, max_length=50, null=True)),
                ('kls_inner_color', models.CharField(blank=True, max_length=50, null=True)),
                ('kls_color', models.CharField(blank=True, max_length=50, null=True)),
                ('ves_gp', models.CharField(blank=True, max_length=150, null=True)),
                ('sena_za_shtuk', models.FloatField(blank=True, null=True)),
                ('sena_za_metr', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
