# Generated by Django 3.2.15 on 2023-03-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ves_del_odxod',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
