# Generated by Django 3.2.18 on 2023-03-25 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_ves_del_odxod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id']},
        ),
    ]
