# Generated by Django 3.2.20 on 2023-12-15 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normabenkam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kraska',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_code_s4q100', models.CharField(blank=True, max_length=255, null=True)),
                ('название', models.CharField(blank=True, max_length=255, null=True)),
                ('еи', models.CharField(blank=True, max_length=255, null=True)),
                ('склад_закупа', models.CharField(blank=True, max_length=255, null=True)),
                ('бренд_краски', models.CharField(blank=True, max_length=255, null=True)),
                ('код_краски', models.CharField(blank=True, max_length=255, null=True)),
                ('тип_краски', models.CharField(blank=True, max_length=255, null=True)),
                ('код_краски_в_профилях', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
