# Generated by Django 3.2.20 on 2023-12-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normabenkam', '0003_ximikat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skotch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_code_s4q100', models.CharField(blank=True, max_length=255, null=True)),
                ('название', models.CharField(blank=True, max_length=255, null=True)),
                ('еи', models.CharField(blank=True, max_length=255, null=True)),
                ('склад_закупа', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubDekorPlonka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_code_s4q100', models.CharField(blank=True, max_length=255, null=True)),
                ('название', models.CharField(blank=True, max_length=255, null=True)),
                ('еи', models.CharField(blank=True, max_length=255, null=True)),
                ('склад_закупа', models.CharField(blank=True, max_length=255, null=True)),
                ('код_декор_пленки', models.CharField(blank=True, max_length=255, null=True)),
                ('ширина_декор_пленки_мм', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
