# Generated by Django 3.2.20 on 2023-12-18 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('normabenkam', '0006_anod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='norma',
            name='header',
        ),
    ]
