# Generated by Django 4.0 on 2023-12-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normabenkam', '0009_auto_20231218_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Termomost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
