# Generated by Django 4.0 on 2023-12-22 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('normabenkam', '0012_filesall'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilesAll',
        ),
    ]
