# Generated by Django 3.2.20 on 2023-12-23 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('normabenkam', '0013_delete_filesall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='texcartabase',
            name='kratkiytekst',
        ),
    ]
