# Generated by Django 4.0 on 2023-12-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normabenkam', '0014_remove_texcartabase_kratkiytekst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kraska',
            name='еи',
            field=models.CharField(blank=True, default='КГ', max_length=255, null=True),
        ),
    ]
