# Generated by Django 3.2.18 on 2023-03-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AluminiyProductBasetermo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ekstruziya_sap_kod', models.CharField(blank=True, max_length=255, null=True)),
                ('ekstruziya_kratkiy_tekst', models.CharField(blank=True, max_length=255, null=True)),
                ('zakalka_sap_kod', models.CharField(blank=True, max_length=255, null=True)),
                ('zakalka_kratkiy_tekst', models.CharField(blank=True, max_length=255, null=True)),
                ('pokraska_sap_kod', models.CharField(blank=True, max_length=255, null=True)),
                ('pokraska_kratkiy_tekst', models.CharField(blank=True, max_length=255, null=True)),
                ('sublimatsiya_sap_kod', models.CharField(blank=True, max_length=255, null=True)),
                ('sublimatsiya_kratkiy_tekst', models.CharField(blank=True, max_length=255, null=True)),
                ('anodirovka_sap_kod', models.CharField(blank=True, max_length=255, null=True)),
                ('anodirovka_kratkiy_tekst', models.CharField(blank=True, max_length=255, null=True)),
                ('laminatsiya_sap_kod', models.CharField(blank=True, max_length=255, null=True)),
                ('laminatsiya_kratkiy_tekst', models.CharField(blank=True, max_length=255, null=True)),
                ('nakleyka_sap_kod', models.CharField(blank=True, max_length=255, null=True)),
                ('nakleyka_kratkiy_tekst', models.CharField(blank=True, max_length=255, null=True)),
                ('upakovka_sap_kod', models.CharField(blank=True, max_length=255, null=True)),
                ('upakovka_kratkiy_tekst', models.CharField(blank=True, max_length=255, null=True)),
                ('fabrikatsiya_sap_kod', models.CharField(blank=True, max_length=255, null=True)),
                ('fabrikatsiya_kratkiy_tekst', models.CharField(blank=True, max_length=255, null=True)),
                ('upakovka2_sap_kod', models.CharField(blank=True, max_length=255, null=True)),
                ('upakovka2_kratkiy_tekst', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AluminiyProductTermo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(blank=True, max_length=250, null=True)),
                ('artikul', models.CharField(blank=True, max_length=250, null=True)),
                ('section', models.CharField(blank=True, max_length=100, null=True)),
                ('counter', models.IntegerField(default=0)),
                ('gruppa_materialov', models.CharField(blank=True, max_length=250, null=True)),
                ('kratkiy_tekst_materiala', models.CharField(blank=True, max_length=250, null=True)),
                ('kombinirovanniy', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
