# Generated by Django 3.2.18 on 2023-04-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluminiytermo', '0003_characteristika'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharUtilsFour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('price_for_1kg_som', models.CharField(blank=True, max_length=255, null=True)),
                ('price_for_1kg_usd', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CharUtilsOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('матрица', models.CharField(blank=True, max_length=255, null=True)),
                ('артикул', models.CharField(blank=True, max_length=255, null=True)),
                ('высота', models.CharField(blank=True, max_length=255, null=True)),
                ('ширина', models.CharField(blank=True, max_length=255, null=True)),
                ('высота_ширина', models.CharField(blank=True, max_length=255, null=True)),
                ('systems', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CharUtilsThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bux_name_rus', models.CharField(blank=True, max_length=255, null=True)),
                ('bux_name_eng', models.CharField(blank=True, max_length=255, null=True)),
                ('tnved', models.CharField(blank=True, max_length=255, null=True)),
                ('group_price', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CharUtilsTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('артикул', models.CharField(blank=True, max_length=255, null=True)),
                ('полый_или_фасонный', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
