# Generated by Django 3.2.18 on 2023-04-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluminiytermo', '0004_charutilsfour_charutilsone_charutilsthree_charutilstwo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacteristicTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('дата_изменение_добавление', models.CharField(blank=True, max_length=255, null=True)),
                ('статус_изменение_добавление', models.CharField(blank=True, max_length=255, null=True)),
                ('ссылки_для_чертежа', models.CharField(blank=True, max_length=255, null=True)),
                ('sap_код_s4p_100', models.CharField(blank=True, max_length=255, null=True)),
                ('нумерация_до_sap', models.CharField(blank=True, max_length=255, null=True)),
                ('короткое_название_sap', models.CharField(blank=True, max_length=255, null=True)),
                ('польное_наименование_sap', models.CharField(blank=True, max_length=255, null=True)),
                ('ед_изм', models.CharField(blank=True, max_length=255, null=True)),
                ('альтернативная_ед_изм', models.CharField(blank=True, max_length=255, null=True)),
                ('коэфициент_пересчета', models.CharField(blank=True, max_length=255, null=True)),
                ('участок', models.CharField(blank=True, max_length=255, null=True)),
                ('альтернативный_участок', models.CharField(blank=True, max_length=255, null=True)),
                ('длина', models.CharField(blank=True, max_length=255, null=True)),
                ('ширина', models.CharField(blank=True, max_length=255, null=True)),
                ('высота', models.CharField(blank=True, max_length=255, null=True)),
                ('группа_материалов', models.CharField(blank=True, max_length=255, null=True)),
                ('удельный_вес_за_метр', models.CharField(blank=True, max_length=255, null=True)),
                ('общий_вес_за_штуку', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
