# Generated by Django 3.2.18 on 2023-04-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluminiytermo', '0005_characteristictitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='BazaProfiley',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('артикул', models.CharField(blank=True, max_length=255, null=True)),
                ('серия', models.CharField(blank=True, max_length=255, null=True)),
                ('старый_код_benkam', models.CharField(blank=True, max_length=255, null=True)),
                ('старый_код', models.CharField(blank=True, max_length=255, null=True)),
                ('old_product_description', models.CharField(blank=True, max_length=255, null=True)),
                ('компонент', models.CharField(blank=True, max_length=255, null=True)),
                ('product_description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
