# Generated by Django 3.2.18 on 2023-04-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluminiytermo', '0006_bazaprofiley'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristictitle',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
