# Generated by Django 3.2.18 on 2023-04-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluminiytermo', '0009_nakleykacode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alufiletermo',
            name='file',
            field=models.FileField(upload_to='uploads/aluminiytermo/downloads/'),
        ),
    ]
