# Generated by Django 4.2.1 on 2023-07-04 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluminiytermo', '0012_characteristikafile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AluminiyProductBasetermo',
        ),
    ]
