# Generated by Django 4.2.1 on 2023-07-04 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluminiytermo', '0013_delete_aluminiyproductbasetermo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bazaprofiley',
            name='old_product_description',
        ),
        migrations.RemoveField(
            model_name='bazaprofiley',
            name='старый_код_benkam',
        ),
    ]
