# Generated by Django 4.2.1 on 2023-07-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluminiytermo', '0014_remove_bazaprofiley_old_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bazaprofiley',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
