# Generated by Django 3.2.20 on 2023-10-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluminiytermo', '0015_bazaprofiley_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='bazaprofiley',
            name='type_combination',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
