# Generated by Django 3.2.20 on 2023-11-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluminiytermo', '0017_messagefeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagefeedback',
            name='msg_type',
            field=models.SmallIntegerField(choices=[(1, 'CHAT'), (2, 'ERROR')], default=1),
        ),
    ]
