# Generated by Django 3.2.20 on 2023-11-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluminiytermo', '0018_messagefeedback_msg_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagefeedback',
            name='parent',
            field=models.IntegerField(default=0),
        ),
    ]
