# Generated by Django 3.2.20 on 2023-11-21 06:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('aluminiytermo', '0019_messagefeedback_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagefeedback',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
