# Generated by Django 3.2.20 on 2023-11-21 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluminiytermo', '0020_messagefeedback_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagefeedback',
            name='last_msg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aluminiytermo.messagefeedback'),
        ),
    ]
