# Generated by Django 5.0.4 on 2024-05-09 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluminiytermo', '0022_alter_bazaprofiley_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BazaProfiley',
        ),
        migrations.DeleteModel(
            name='CharUtilsOne',
        ),
        migrations.DeleteModel(
            name='CharUtilsTwo',
        ),
    ]
