# Generated by Django 5.0.4 on 2024-05-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluminiytermo', '0024_artikulcomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='nakleykacode',
            name='nadpis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
