# Generated by Django 5.0.4 on 2024-11-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluminiytermo', '0025_nakleykacode_nadpis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristika',
            name='export_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='characteristika',
            name='export_description_eng',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
