# Generated by Django 5.0.4 on 2024-11-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluminiytermo', '0026_alter_characteristika_export_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristika',
            name='export_description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='characteristika',
            name='export_description_eng',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
