# Generated by Django 3.2.18 on 2023-04-01 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='norma',
            old_name='мол_скотча_мм',
            new_name='молярный_скотч_ширина1_мол_скотча_мм',
        ),
        migrations.RenameField(
            model_name='norma',
            old_name='молярный_скотч_ширина1',
            new_name='молярный_скотч_ширина2_мол_скотча_мм',
        ),
        migrations.RemoveField(
            model_name='norma',
            name='молярный_скотч_ширина2',
        ),
    ]
