# Generated by Django 3.2.18 on 2023-04-01 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0002_auto_20230331_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlyuminniysilindrEkstruziya1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_code_s4q100', models.CharField(blank=True, max_length=255, null=True)),
                ('название', models.CharField(blank=True, max_length=255, null=True)),
                ('еи', models.CharField(blank=True, max_length=255, null=True)),
                ('склад_закупа', models.CharField(blank=True, max_length=255, null=True)),
                ('тип', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlyuminniysilindrEkstruziya2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_code_s4q100', models.CharField(blank=True, max_length=255, null=True)),
                ('название', models.CharField(blank=True, max_length=255, null=True)),
                ('еи', models.CharField(blank=True, max_length=255, null=True)),
                ('склад_закупа', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KleyDlyaLamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_code_s4q100', models.CharField(blank=True, max_length=255, null=True)),
                ('название', models.CharField(blank=True, max_length=255, null=True)),
                ('еи', models.CharField(blank=True, max_length=255, null=True)),
                ('склад_закупа', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kraska',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_code_s4q100', models.CharField(blank=True, max_length=255, null=True)),
                ('название', models.CharField(blank=True, max_length=255, null=True)),
                ('еи', models.CharField(blank=True, max_length=255, null=True)),
                ('склад_закупа', models.CharField(blank=True, max_length=255, null=True)),
                ('бренд_краски', models.CharField(blank=True, max_length=255, null=True)),
                ('код_краски', models.CharField(blank=True, max_length=255, null=True)),
                ('тип_краски', models.CharField(blank=True, max_length=255, null=True)),
                ('код_краски_в_профилях', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lamplonka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_code_s4q100', models.CharField(blank=True, max_length=255, null=True)),
                ('название', models.CharField(blank=True, max_length=255, null=True)),
                ('еи', models.CharField(blank=True, max_length=255, null=True)),
                ('склад_закупа', models.CharField(blank=True, max_length=255, null=True)),
                ('код_лам_пленки', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nakleyka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_code_s4q100', models.CharField(blank=True, max_length=255, null=True)),
                ('название', models.CharField(blank=True, max_length=255, null=True)),
                ('еи', models.CharField(blank=True, max_length=255, null=True)),
                ('склад_закупа', models.CharField(blank=True, max_length=255, null=True)),
                ('код_наклейки', models.CharField(blank=True, max_length=255, null=True)),
                ('название_наклейки', models.CharField(blank=True, max_length=255, null=True)),
                ('ширина', models.CharField(blank=True, max_length=255, null=True)),
                ('еи_ширины', models.CharField(blank=True, max_length=255, null=True)),
                ('тип_клея', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProchiyeSiryoNeno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_code_s4q100', models.CharField(blank=True, max_length=255, null=True)),
                ('название', models.CharField(blank=True, max_length=255, null=True)),
                ('еи', models.CharField(blank=True, max_length=255, null=True)),
                ('склад_закупа', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiryoDlyaUpakovki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_code_s4q100', models.CharField(blank=True, max_length=255, null=True)),
                ('название', models.CharField(blank=True, max_length=255, null=True)),
                ('еи', models.CharField(blank=True, max_length=255, null=True)),
                ('склад_закупа', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skotch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_code_s4q100', models.CharField(blank=True, max_length=255, null=True)),
                ('название', models.CharField(blank=True, max_length=255, null=True)),
                ('еи', models.CharField(blank=True, max_length=255, null=True)),
                ('склад_закупа', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubDekorPlonka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_code_s4q100', models.CharField(blank=True, max_length=255, null=True)),
                ('название', models.CharField(blank=True, max_length=255, null=True)),
                ('еи', models.CharField(blank=True, max_length=255, null=True)),
                ('склад_закупа', models.CharField(blank=True, max_length=255, null=True)),
                ('код_декор_пленки', models.CharField(blank=True, max_length=255, null=True)),
                ('ширина_декор_пленки_мм', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermomostDlyaTermo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_code_s4q100', models.CharField(blank=True, max_length=255, null=True)),
                ('название', models.CharField(blank=True, max_length=255, null=True)),
                ('еи', models.CharField(blank=True, max_length=255, null=True)),
                ('склад_закупа', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ximikat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_code_s4q100', models.CharField(blank=True, max_length=255, null=True)),
                ('название', models.CharField(blank=True, max_length=255, null=True)),
                ('еи', models.CharField(blank=True, max_length=255, null=True)),
                ('склад_закупа', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
