# Generated by Django 4.2.1 on 2023-05-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0002_accessuar'),
    ]

    operations = [
        migrations.AddField(
            model_name='norma',
            name='алюминиевый_сплав_6063_при_этом_балвашка',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
