# Generated by Django 4.2.1 on 2023-05-25 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0003_norma_алюминиевый_сплав_6063_при_этом_балвашка'),
    ]

    operations = [
        migrations.RenameField(
            model_name='norma',
            old_name='заш_пл_кг_м_ch_бк_ст_ширина_лн_мм',
            new_name='заш_пл_кг_м_голд_бк_ст_ширина_лн_мм',
        ),
        migrations.RenameField(
            model_name='norma',
            old_name='заш_пл_кг_м_ch_вр_ширина_лн_мм',
            new_name='заш_пл_кг_м_голд_вр_ширина_лн_мм',
        ),
        migrations.RenameField(
            model_name='norma',
            old_name='заш_пл_кг_м_ch_низ_рас_лн_на_1000_пр_м2',
            new_name='заш_пл_кг_м_голд_низ_рас_лн_на_1000_пр_м2',
        ),
        migrations.RenameField(
            model_name='norma',
            old_name='заш_пл_кг_м_ch_низ_ширина_лн_мм',
            new_name='заш_пл_кг_м_голд_низ_ширина_лн_мм',
        ),
        migrations.RenameField(
            model_name='norma',
            old_name='кг_м_ch_вр_и_кг_м_ch_бк_ст_рас',
            new_name='кг_м_голд_вр_и_кг_м_голд_бк_ст_рас',
        ),
    ]
