# Generated by Django 4.2.1 on 2023-05-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0004_rename_заш_пл_кг_м_ch_бк_ст_ширина_лн_мм_norma_заш_пл_кг_м_голд_бк_ст_ширина_лн_мм_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kraska',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
