# Generated by Django 3.2.18 on 2023-04-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0004_checknormabase_normaexcelfiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormaDontExistInExcell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artikul', models.CharField(blank=True, max_length=255, null=True)),
                ('kratkiytekst', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
