# Generated by Django 4.2.1 on 2023-05-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0006_nakleykaiskyuchenie'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessuar',
            name='skotch',
            field=models.BooleanField(default=False),
        ),
    ]
