# Generated by Django 3.2.18 on 2023-04-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0006_remove_normadontexistinexcell_kratkiytekst'),
    ]

    operations = [
        migrations.CreateModel(
            name='KombinirovaniyUtilsInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artikul', models.CharField(blank=True, max_length=255, null=True)),
                ('component1', models.CharField(blank=True, max_length=255, null=True)),
                ('component2', models.CharField(blank=True, max_length=255, null=True)),
                ('component3', models.CharField(blank=True, max_length=255, null=True)),
                ('sap_code1', models.CharField(blank=True, max_length=255, null=True)),
                ('termal_bridge1', models.CharField(blank=True, max_length=255, null=True)),
                ('sap_code2', models.CharField(blank=True, max_length=255, null=True)),
                ('termal_bridge2', models.CharField(blank=True, max_length=255, null=True)),
                ('sap_code3', models.CharField(blank=True, max_length=255, null=True)),
                ('termal_bridge3', models.CharField(blank=True, max_length=255, null=True)),
                ('sap_code4', models.CharField(blank=True, max_length=255, null=True)),
                ('termal_bridge4', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
