# Generated by Django 4.2.1 on 2023-07-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0007_accessuar_skotch'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaexcelfiles',
            name='type',
            field=models.CharField(blank=True, default='simple', max_length=20, null=True),
        ),
    ]
