# Generated by Django 3.2.18 on 2023-04-28 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0009_alter_normaexcelfiles_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='norma',
            name='алю_сплав_биллетов_102_178',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
