# Generated by Django 3.2.20 on 2023-10-12 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0014_auto_20231010_1055'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KombinirovaniyUtilsInformation',
        ),
        migrations.DeleteModel(
            name='NakleykaIskyuchenie',
        ),
        migrations.DeleteModel(
            name='TermomostDlyaTermo',
        ),
        migrations.DeleteModel(
            name='ZakalkaIskyuchenie6064',
        ),
    ]
