# Generated by Django 3.2.20 on 2023-11-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0015_auto_20231012_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='norma',
            name='qbic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
