# Generated by Django 3.2.20 on 2023-11-20 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0016_norma_qbic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='norma',
            name='qbic',
        ),
    ]
