# Generated by Django 3.2.20 on 2023-08-31 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imzo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='texcartatime',
            name='ekstruziya',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='texcartatime',
            name='gr_pokras',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='texcartatime',
            name='gr_xim',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='texcartatime',
            name='kom_upakovka',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='texcartatime',
            name='kombinirovan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='texcartatime',
            name='lam_nak_upakovka',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='texcartatime',
            name='nakleyka',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='texcartatime',
            name='pila',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='texcartatime',
            name='ruchnoy_pokraska',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='texcartatime',
            name='sat_pokras',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='texcartatime',
            name='sat_xim',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='texcartatime',
            name='skm_pokras',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='texcartatime',
            name='skm_xim',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='texcartatime',
            name='strayenie',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='texcartatime',
            name='sublimat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='texcartatime',
            name='upakovka',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
