# Generated by Django 3.2.18 on 2023-04-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imzo', '0002_imzobase'),
    ]

    operations = [
        migrations.CreateModel(
            name='TexCartaTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('компонент_1', models.CharField(blank=True, max_length=255, null=True)),
                ('компонент_2', models.CharField(blank=True, max_length=255, null=True)),
                ('компонент_3', models.CharField(blank=True, max_length=255, null=True)),
                ('артикул', models.CharField(blank=True, max_length=255, null=True)),
                ('пресс_1_линия_буй', models.CharField(blank=True, max_length=255, null=True)),
                ('закалка_1_печь_буй', models.CharField(blank=True, max_length=255, null=True)),
                ('покраска_9016_белый_про_во_в_сутки_буй', models.CharField(blank=True, max_length=255, null=True)),
                ('покраска_8001_базовый_про_во_в_сутки_буй', models.CharField(blank=True, max_length=255, null=True)),
                ('покраска_цветной_про_во_в_сутки_буй', models.CharField(blank=True, max_length=255, null=True)),
                ('вакуум_1_печка_про_во_в_сутки_буй', models.CharField(blank=True, max_length=255, null=True)),
                ('термо_1_линия_про_во_в_сутки_буй', models.CharField(blank=True, max_length=255, null=True)),
                ('наклейка_упаковка_1_линия_про_во_в_сутки_буй', models.CharField(blank=True, max_length=255, null=True)),
                ('ламинат_1_линия_про_во_в_сутки_буй', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
