# Generated by Django 3.2.18 on 2023-04-27 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imzo', '0004_alter_excelfilesimzo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfilesimzo',
            name='file',
            field=models.FileField(max_length=500, upload_to='uploads/imzo/downloads'),
        ),
    ]
