# Generated by Django 5.0.4 on 2024-08-29 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epdm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Norma75',
            new_name='NormaEpdm',
        ),
    ]
