# Generated by Django 5.0.4 on 2024-09-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epdm', '0003_texcartafile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiroEpdm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('sapcode', models.CharField(max_length=50)),
                ('kratkiy', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
