# Generated by Django 5.0.4 on 2024-09-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epdm', '0006_rename_code_siroepdm_kg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siroepdm',
            name='kg',
        ),
        migrations.RemoveField(
            model_name='siroepdm',
            name='kratkiy',
        ),
        migrations.RemoveField(
            model_name='siroepdm',
            name='sapcode',
        ),
        migrations.RemoveField(
            model_name='siroepdm',
            name='shop',
        ),
        migrations.AddField(
            model_name='siroepdm',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
