# Generated by Django 5.0.4 on 2024-11-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epdm', '0008_epdmsapcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpdmArtikul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
