# Generated by Django 3.2.15 on 2023-03-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AluminiyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artikul', models.CharField(blank=True, max_length=25, null=True)),
                ('dlina', models.FloatField(default=None)),
                ('tip_pokritiya', models.CharField(blank=True, max_length=100, null=True)),
                ('splav', models.CharField(blank=True, max_length=30, null=True)),
                ('tip_zaklepnosti', models.CharField(blank=True, max_length=15, null=True)),
                ('kombinatsiya', models.CharField(blank=True, max_length=100, null=True)),
                ('brend_kraski', models.CharField(blank=True, max_length=15, null=True)),
                ('kod_kraski_narujiya', models.CharField(blank=True, max_length=50, null=True)),
                ('kod_dekor_plenki_snaruji', models.CharField(blank=True, max_length=50, null=True)),
                ('svet_dekor_plyonki_snaruji', models.CharField(blank=True, max_length=100, null=True)),
                ('kod_nakleyki', models.CharField(blank=True, max_length=25, null=True)),
                ('kratkiy_teks_tovara', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArtikulComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artikul', models.CharField(blank=True, max_length=250, null=True)),
                ('component', models.CharField(blank=True, max_length=250, null=True)),
                ('seria', models.CharField(blank=True, max_length=250, null=True)),
                ('product_description_ru', models.CharField(blank=True, max_length=250, null=True)),
                ('proverka_artikul2', models.CharField(blank=True, max_length=250, null=True)),
                ('proverka_component2', models.CharField(blank=True, max_length=250, null=True)),
                ('gruppa_materialov', models.CharField(blank=True, max_length=250, null=True)),
                ('gruppa_materialov2', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
