# Generated by Django 3.2.18 on 2023-03-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluminiy', '0003_aluminiyproductbase'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikulcomponent',
            name='product_description_ru1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
