# Generated by Django 3.2.18 on 2023-03-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluminiy', '0004_artikulcomponent_product_description_ru1'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikulcomponent',
            name='stariy_code_benkam',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='artikulcomponent',
            name='stariy_code_jomiy',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
