# Generated by Django 3.2.18 on 2023-03-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluminiy', '0006_auto_20230314_0511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluminiyproduct',
            old_name='kratkiy_teks_tovara',
            new_name='counter',
        ),
        migrations.RenameField(
            model_name='aluminiyproduct',
            old_name='kombinatsiya',
            new_name='section',
        ),
        migrations.RemoveField(
            model_name='aluminiyproduct',
            name='brend_kraski',
        ),
        migrations.RemoveField(
            model_name='aluminiyproduct',
            name='dlina',
        ),
        migrations.RemoveField(
            model_name='aluminiyproduct',
            name='kod_dekor_plenki_snaruji',
        ),
        migrations.RemoveField(
            model_name='aluminiyproduct',
            name='kod_kraski_narujiya',
        ),
        migrations.RemoveField(
            model_name='aluminiyproduct',
            name='kod_nakleyki',
        ),
        migrations.RemoveField(
            model_name='aluminiyproduct',
            name='splav',
        ),
        migrations.RemoveField(
            model_name='aluminiyproduct',
            name='svet_dekor_plyonki_snaruji',
        ),
        migrations.RemoveField(
            model_name='aluminiyproduct',
            name='tip_pokritiya',
        ),
        migrations.RemoveField(
            model_name='aluminiyproduct',
            name='tip_zaklepnosti',
        ),
        migrations.AddField(
            model_name='aluminiyproduct',
            name='gruppa_materialov',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='aluminiyproduct',
            name='kombinirovanniy',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='aluminiyproduct',
            name='kratkiy_tekst_materiala',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='aluminiyproduct',
            name='material',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='aluminiyproduct',
            name='artikul',
            field=models.FloatField(default=None),
        ),
    ]
