# Generated by Django 3.2.18 on 2023-03-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluminiy', '0007_auto_20230315_0437'),
    ]

    operations = [
        migrations.CreateModel(
            name='AluminiyProductTermo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(blank=True, max_length=250, null=True)),
                ('artikul', models.FloatField(default=None)),
                ('section', models.CharField(blank=True, max_length=100, null=True)),
                ('counter', models.CharField(blank=True, max_length=250, null=True)),
                ('gruppa_materialov', models.CharField(blank=True, max_length=250, null=True)),
                ('kratkiy_tekst_materiala', models.CharField(blank=True, max_length=250, null=True)),
                ('kombinirovanniy', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
