# Generated by Django 3.2.18 on 2023-03-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluminiy', '0008_aluminiyproducttermo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluminiyproduct',
            name='artikul',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='aluminiyproducttermo',
            name='artikul',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
