# Generated by Django 3.2.18 on 2023-03-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluminiy', '0009_auto_20230315_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluminiyproduct',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aluminiyproducttermo',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
