# Generated by Django 3.2.18 on 2023-03-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluminiy', '0010_auto_20230315_0455'),
    ]

    operations = [
        migrations.CreateModel(
            name='AluminiyProductBasesimple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ekstruziya_sap_kod', models.CharField(blank=True, max_length=255, null=True)),
                ('ekstruziya_kratkiy_tekst', models.CharField(blank=True, max_length=255, null=True)),
                ('zakalka_sap_kod', models.CharField(blank=True, max_length=255, null=True)),
                ('zakalka_kratkiy_tekst', models.CharField(blank=True, max_length=255, null=True)),
                ('pokraska_sap_kod', models.CharField(blank=True, max_length=255, null=True)),
                ('pokraska_kratkiy_tekst', models.CharField(blank=True, max_length=255, null=True)),
                ('sublimatsiya_sap_kod', models.CharField(blank=True, max_length=255, null=True)),
                ('sublimatsiya_kratkiy_tekst', models.CharField(blank=True, max_length=255, null=True)),
                ('anodirovka_sap_kod', models.CharField(blank=True, max_length=255, null=True)),
                ('anodirovka_kratkiy_tekst', models.CharField(blank=True, max_length=255, null=True)),
                ('laminatsiya_sap_kod', models.CharField(blank=True, max_length=255, null=True)),
                ('laminatsiya_kratkiy_tekst', models.CharField(blank=True, max_length=255, null=True)),
                ('nakleyka_sap_kod', models.CharField(blank=True, max_length=255, null=True)),
                ('nakleyka_kratkiy_tekst', models.CharField(blank=True, max_length=255, null=True)),
                ('upakovka_sap_kod', models.CharField(blank=True, max_length=255, null=True)),
                ('upakovka_kratkiy_tekst', models.CharField(blank=True, max_length=255, null=True)),
                ('fabrikatsiya_sap_kod', models.CharField(blank=True, max_length=255, null=True)),
                ('fabrikatsiya_kratkiy_tekst', models.CharField(blank=True, max_length=255, null=True)),
                ('upakovka2_sap_kod', models.CharField(blank=True, max_length=255, null=True)),
                ('upakovka2_kratkiy_tekst', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AluminiyProductBasetermo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ekstruziya_sap_kod', models.CharField(blank=True, max_length=255, null=True)),
                ('ekstruziya_kratkiy_tekst', models.CharField(blank=True, max_length=255, null=True)),
                ('zakalka_sap_kod', models.CharField(blank=True, max_length=255, null=True)),
                ('zakalka_kratkiy_tekst', models.CharField(blank=True, max_length=255, null=True)),
                ('pokraska_sap_kod', models.CharField(blank=True, max_length=255, null=True)),
                ('pokraska_kratkiy_tekst', models.CharField(blank=True, max_length=255, null=True)),
                ('sublimatsiya_sap_kod', models.CharField(blank=True, max_length=255, null=True)),
                ('sublimatsiya_kratkiy_tekst', models.CharField(blank=True, max_length=255, null=True)),
                ('anodirovka_sap_kod', models.CharField(blank=True, max_length=255, null=True)),
                ('anodirovka_kratkiy_tekst', models.CharField(blank=True, max_length=255, null=True)),
                ('laminatsiya_sap_kod', models.CharField(blank=True, max_length=255, null=True)),
                ('laminatsiya_kratkiy_tekst', models.CharField(blank=True, max_length=255, null=True)),
                ('nakleyka_sap_kod', models.CharField(blank=True, max_length=255, null=True)),
                ('nakleyka_kratkiy_tekst', models.CharField(blank=True, max_length=255, null=True)),
                ('upakovka_sap_kod', models.CharField(blank=True, max_length=255, null=True)),
                ('upakovka_kratkiy_tekst', models.CharField(blank=True, max_length=255, null=True)),
                ('fabrikatsiya_sap_kod', models.CharField(blank=True, max_length=255, null=True)),
                ('fabrikatsiya_kratkiy_tekst', models.CharField(blank=True, max_length=255, null=True)),
                ('upakovka2_sap_kod', models.CharField(blank=True, max_length=255, null=True)),
                ('upakovka2_kratkiy_tekst', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AluminiyProductBase',
        ),
    ]
