# Generated by Django 3.2.18 on 2023-03-28 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluminiy', '0011_auto_20230315_1539'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AluminiyProductBasetermo',
        ),
        migrations.DeleteModel(
            name='AluminiyProductTermo',
        ),
    ]
