# Generated by Django 3.2.18 on 2023-04-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluminiy', '0012_auto_20230328_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='alufile',
            name='file_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
