# Generated by Django 3.2.18 on 2023-04-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluminiy', '0013_alufile_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alufile',
            name='file',
            field=models.FileField(upload_to='uploads/aluminiy/downloads/'),
        ),
    ]
