# Generated by Django 4.2.1 on 2023-06-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluminiy', '0015_alter_alufile_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazlovkaObichniy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esap_code', models.CharField(max_length=100)),
                ('ekratkiy', models.CharField(max_length=150)),
                ('zsap_code', models.CharField(max_length=100)),
                ('zkratkiy', models.CharField(max_length=150)),
                ('psap_code', models.CharField(max_length=100)),
                ('pkratkiy', models.CharField(max_length=150)),
                ('ssap_code', models.CharField(max_length=100)),
                ('skratkiy', models.CharField(max_length=150)),
                ('asap_code', models.CharField(max_length=100)),
                ('akratkiy', models.CharField(max_length=150)),
                ('lsap_code', models.CharField(max_length=100)),
                ('lkratkiy', models.CharField(max_length=150)),
                ('nsap_code', models.CharField(max_length=100)),
                ('nkratkiy', models.CharField(max_length=150)),
                ('sap_code7', models.CharField(max_length=100)),
                ('kratkiy7', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RazlovkaTermo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esap_code', models.CharField(max_length=100)),
                ('ekratkiy', models.CharField(max_length=150)),
                ('zsap_code', models.CharField(max_length=100)),
                ('zkratkiy', models.CharField(max_length=150)),
                ('psap_code', models.CharField(max_length=100)),
                ('pkratkiy', models.CharField(max_length=150)),
                ('ssap_code', models.CharField(max_length=100)),
                ('skratkiy', models.CharField(max_length=150)),
                ('asap_code', models.CharField(max_length=100)),
                ('akratkiy', models.CharField(max_length=150)),
                ('nsap_code', models.CharField(max_length=100)),
                ('nkratkiy', models.CharField(max_length=150)),
                ('ksap_code', models.CharField(max_length=100)),
                ('kratkiy', models.CharField(max_length=150)),
                ('lsap_code', models.CharField(max_length=100)),
                ('lkratkiy', models.CharField(max_length=150)),
                ('sap_code7', models.CharField(max_length=100)),
                ('kratkiy7', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
