# Generated by Django 4.2.1 on 2023-06-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluminiy', '0016_razlovkaobichniy_razlovkatermo'),
    ]

    operations = [
        migrations.AddField(
            model_name='razlovkatermo',
            name='parent_id',
            field=models.IntegerField(default=0),
        ),
    ]
