# Generated by Django 4.2.1 on 2023-07-04 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluminiy', '0017_razlovkatermo_parent_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AluminiyProductBasesimple',
        ),
        migrations.RemoveField(
            model_name='artikulcomponent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='artikulcomponent',
            name='gruppa_materialov',
        ),
        migrations.RemoveField(
            model_name='artikulcomponent',
            name='gruppa_materialov2',
        ),
        migrations.RemoveField(
            model_name='artikulcomponent',
            name='product_description_ru',
        ),
        migrations.RemoveField(
            model_name='artikulcomponent',
            name='product_description_ru1',
        ),
        migrations.RemoveField(
            model_name='artikulcomponent',
            name='proverka_artikul2',
        ),
        migrations.RemoveField(
            model_name='artikulcomponent',
            name='proverka_component2',
        ),
        migrations.RemoveField(
            model_name='artikulcomponent',
            name='seria',
        ),
        migrations.RemoveField(
            model_name='artikulcomponent',
            name='stariy_code_benkam',
        ),
        migrations.RemoveField(
            model_name='artikulcomponent',
            name='stariy_code_jomiy',
        ),
        migrations.RemoveField(
            model_name='artikulcomponent',
            name='updated_at',
        ),
    ]
