# Generated by Django 4.2.1 on 2023-07-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluminiy', '0018_delete_aluminiyproductbasesimple_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewAndOld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artikul', models.CharField(max_length=50)),
                ('komponent', models.CharField(max_length=50)),
                ('oldername', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
