# Generated by Django 4.2.1 on 2023-07-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluminiy', '0019_newandold'),
    ]

    operations = [
        migrations.AddField(
            model_name='razlovkaobichniy',
            name='fkratkiy',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='razlovkaobichniy',
            name='fsap_code',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='razlovkaobichniy',
            name='kratkiy75',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='razlovkaobichniy',
            name='sap_code75',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='razlovkatermo',
            name='fkratkiy',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='razlovkatermo',
            name='fsap_code',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='razlovkatermo',
            name='kratkiy75',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='razlovkatermo',
            name='sap_code75',
            field=models.CharField(default='', max_length=100),
        ),
    ]
