# Generated by Django 3.2.20 on 2023-10-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluminiy', '0024_exchangevalues'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangevalues',
            name='data',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
