# Generated by Django 3.2.20 on 2023-10-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluminiy', '0025_exchangevalues_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangevalues',
            old_name='data',
            new_name='end_data',
        ),
        migrations.AddField(
            model_name='exchangevalues',
            name='start_data',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
