# Generated by Django 4.0 on 2023-11-29 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluminiy', '0026_auto_20231026_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikulcomponent',
            name='baza_profile',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='artikulcomponent',
            name='code_nakleyka',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artikulcomponent',
            name='combination',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artikulcomponent',
            name='system',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
