# Generated by Django 5.0.4 on 2024-05-09 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluminiy', '0029_alufilebazaprofiles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArtikulComponent',
        ),
    ]
