# Generated by Django 5.0.4 on 2024-07-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluminiy', '0030_delete_artikulcomponent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrendKraska',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brend', models.CharField(blank=True, max_length=10, null=True)),
                ('kraska', models.CharField(blank=True, max_length=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
