# Generated by Django 5.0.4 on 2024-07-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluminiy', '0031_brendkraska'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mastergroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sep', models.CharField(blank=True, max_length=40, null=True)),
                ('pokritiya', models.CharField(blank=True, max_length=40, null=True)),
                ('combination', models.CharField(blank=True, max_length=40, null=True)),
                ('new_group', models.CharField(blank=True, max_length=40, null=True)),
                ('sena_usd', models.CharField(blank=True, max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
