# Generated by Django 5.0.4 on 2024-10-28 09:47

import aluminiy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluminiy', '0037_alter_lengthofprofile_ves_za_metr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lengthofprofile',
            name='ves_za_metr',
            field=models.JSONField(blank=True, default=aluminiy.models.default_ves_za_metr, null=True),
        ),
        migrations.AlterField(
            model_name='lengthofprofile',
            name='ves_za_shtuk',
            field=models.JSONField(blank=True, default=aluminiy.models.default_ves_za_shtuk, null=True),
        ),
    ]
