# Generated by Django 3.2.20 on 2023-08-10 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('status', models.SmallIntegerField(choices=[(1, 'ON HOLD'), (2, 'ON PROCESS'), (3, 'CANCEL'), (4, 'DONE')], default=1)),
                ('work_type', models.SmallIntegerField(choices=[(1, 'SAP CODE CREATING'), (2, 'SAP CODE CREATING LACKS'), (3, 'TEXT CREATING'), (4, 'TEXT CREATING LACKS'), (5, 'NORMA'), (6, 'NORMA CREATING LACKS'), (7, 'TEXCARTA'), (8, 'VI')], default=1)),
                ('paths', jsonfield.fields.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alumin_wrongs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aluminiy_work_wrong', to=settings.AUTH_USER_MODEL)),
                ('aluminiy_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aluminiy_work', to=settings.AUTH_USER_MODEL)),
                ('norma_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='norma_work', to=settings.AUTH_USER_MODEL)),
                ('norma_wrongs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='norma_work_wrong', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('texcarta_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='texcarta_work', to=settings.AUTH_USER_MODEL)),
                ('vi_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vi_work', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
