# Generated by Django 3.2.20 on 2023-08-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_current_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paths',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_type',
            field=models.SmallIntegerField(choices=[(1, 'ON HOLD'), (2, 'SAP CODE CREATING'), (3, 'SAP CODE CREATING LACKS'), (4, 'TEXT CREATING'), (5, 'TEXT CREATING LACKS'), (6, 'NORMA'), (7, 'NORMA CREATING LACKS'), (8, 'TEXCARTA'), (9, 'VI')], default=1),
        ),
    ]
