# Generated by Django 3.2.20 on 2023-08-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_alumin_text_wrongs'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.SmallIntegerField(choices=[(1, 'ОБЫЧНЫЙ'), (2, 'ТЕРМО')], default=1),
        ),
    ]
