# Generated by Django 3.2.20 on 2023-09-26 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0006_alter_order_work_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPVX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('status', models.SmallIntegerField(choices=[(1, 'ON HOLD'), (2, 'ON PROCESS'), (3, 'CANCEL'), (4, 'DONE')], default=1)),
                ('work_type', models.SmallIntegerField(choices=[(1, 'ON HOLD'), (2, 'SAP CODE CREATING'), (3, 'SAP CODE CREATING LACKS'), (4, 'TEXT CREATING'), (5, 'TEXT CREATING LACKS'), (6, 'NORMA'), (7, 'NORMA CREATING LACKS'), (8, 'TEXCARTA'), (9, 'VI'), (10, 'DONE')], default=1)),
                ('paths', models.JSONField(blank=True, default=dict, null=True)),
                ('order_type', models.SmallIntegerField(choices=[(1, 'ОБЫЧНЫЙ'), (2, 'ТЕРМО')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alumin_wrongs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pvc_work_wrong', to=settings.AUTH_USER_MODEL)),
                ('current_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='on_time_worker_pvc', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pvc_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pvc_work', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
