# Generated by Django 3.2.20 on 2023-09-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_orderpvx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpvx',
            name='order_type',
            field=models.SmallIntegerField(choices=[(1, 'ЛАМ'), (2, 'БЕЗ ЛАМ')], default=1),
        ),
    ]
