# Generated by Django 3.2.20 on 2023-09-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_rename_alumin_wrongs_orderpvx_pvc_wrongs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpvx',
            name='work_type',
            field=models.SmallIntegerField(choices=[(1, 'ON HOLD'), (2, 'SAP CODE CREATING'), (3, 'SAP CODE CREATING LACKS'), (4, 'TEXT CREATING'), (5, 'TEXT CREATING LACKS'), (10, 'DONE')], default=1),
        ),
    ]
