# Generated by Django 3.2.20 on 2023-10-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_orderpvx_work_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpvx',
            name='work_type',
            field=models.SmallIntegerField(choices=[(1, 'ON HOLD'), (2, 'SAP CODE CREATING'), (3, 'SAP CODE CREATING LACKS'), (4, 'TEXT CREATING'), (5, 'TEXT CREATING LACKS'), (6, 'DONE')], default=1),
        ),
    ]
