# Generated by Django 5.0.4 on 2024-08-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_orderpvx_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_order_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
