# Generated by Django 5.0.4 on 2024-08-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_order_client_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpvx',
            name='client_order_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
